-- CREATE TABLE IF NOT EXISTS temp(
--    id                   BIGINT AUTO_INCREMENT PRIMARY KEY
--   ,temp                 VARCHAR(256) NULL
-- );

-- CREATE TABLE IF NOT EXISTS highscore (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    score INTEGER,
--    timestamp TIMESTAMP,
--    username VARCHAR(255)
-- );
